# Generated by Django 2.1.3 on 2018-11-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181119_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='name',
            field=models.CharField(default=None, max_length=64, verbose_name='学员姓名'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='referral_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.CustomerInfo', verbose_name='转介绍'),
        ),
    ]
