# Generated by Django 2.1.3 on 2018-11-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='学院ID')),
                ('name', models.CharField(max_length=255, verbose_name='学院名称')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
