# Generated by Django 2.1.3 on 2018-11-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=34, verbose_name='姓名'),
        ),
    ]
